In [1]:
import tensorflow as tf
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
train_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

In [17]:
test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype('float32')/255

In [18]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [19]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 6s 97us/step - loss: 0.2564 - acc: 0.9261
Epoch 2/5
60000/60000 [==============================] - 5s 80us/step - loss: 0.1038 - acc: 0.9687
Epoch 3/5
60000/60000 [==============================] - 5s 80us/step - loss: 0.0681 - acc: 0.9802
Epoch 4/5
60000/60000 [==============================] - 5s 80us/step - loss: 0.0492 - acc: 0.9857
Epoch 5/5
60000/60000 [==============================] - 5s 80us/step - loss: 0.0374 - acc: 0.9886


In [20]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 51us/step


In [21]:
print('test_acc:', test_acc)

test_acc: 0.0892


In [24]:
#0D tensors --> Scalars
import numpy as np
x=np.array(12)
x,x.ndim

(array(12), 0)

In [25]:
#Vectors 1D Tensors
x=np.array([1,2,3,4])
x, x.ndim, x.shape


(array([1, 2, 3, 4]), 1, (4,))

In [26]:
#Matrices 2D Tensors
x = np.array([[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]])
x,x.ndim,x.shape

(array([[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]), 2, (3, 5))

In [27]:
x = np.array([[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]]])
x,x.ndim,x.shape

(array([[[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]],
 
        [[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]],
 
        [[ 5, 78,  2, 34,  0],
         [ 6, 79,  3, 35,  1],
         [ 7, 80,  4, 36,  2]]]), 3, (3, 3, 5))