In [4]:
#Vectorized is something which has position.

In [5]:
alist=[1,2,3,4,5]
empty=[]
for num in alist:
    empty.append(num*5)
empty

[5, 10, 15, 20, 25]

In [1]:
import numpy as np #numpy is fast and works on vectorization

In [3]:
numbers=np.array([2,3,4,6,7,8])
numbers*4

array([ 8, 12, 16, 24, 28, 32])

In [8]:
from numpy import *

In [21]:
numbers=array([2,3,4,6,7,8])
no=numbers*4
no

array([ 8, 12, 16, 24, 28, 32])

In [22]:
no >10

array([False,  True,  True,  True,  True,  True])

In [12]:
a1=np.array([2,3,4,4.0,5.0])
a1

array([2., 3., 4., 4., 5.])

In [13]:
a2=np.array([2,3,4,4.0,5.0],dtype=int)
a2

array([2, 3, 4, 4, 5])

In [14]:
def squares (values):
    result=[]
    for v in values:
        result.append(v*v)
    return result

In [15]:
to_square=range(100000)

In [17]:
%timeit squares(to_square) #any keyword with % sign is magic function

16.7 ms ± 56.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
array_square=np.arange(100000)

In [19]:
%timeit array_square**2

156 µs ± 484 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
type(a2)

numpy.ndarray

In [26]:
np.size(a2)

5

In [28]:
len(a2)

5

In [29]:
a3=np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
q=np.ones(5)
q

array([1., 1., 1., 1., 1.])

In [36]:
np.zeros_like(q)

array([0., 0., 0., 0., 0.])

In [40]:
np.ones_like(q)

array([1., 1., 1., 1., 1.])

In [42]:
x=np.array([3,6,9])
np.ones_like(x)

array([1, 1, 1])

In [51]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [58]:
a1+a2

array([ 4.,  6.,  8.,  8., 10.])

# 2D Numpy

In [78]:
_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [79]:
_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
np.size(_2d)

12

In [81]:
len(_2d)

4

In [82]:
_2d.shape

(4, 3)

In [99]:
_2D=np.arange(20).reshape(5,4)
_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [100]:
np.size(_2D)

20

In [101]:
np.size(_2D,0) #ye rows batayega

5

In [103]:
np.size(_2D,1) #ye columns batarega

4

In [104]:
np.shape(_2D)

(5, 4)

In [106]:
_2D.reshape(20) #It is one dimension.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
import math
tdarray=np.random.randn(20).reshape(5,4)
tdarray

array([[-0.1251118 , -0.0540305 ,  1.11397485, -0.64487159],
       [-0.12166057, -1.45964744, -0.27998011,  2.2346097 ],
       [ 0.11485135, -1.23472826,  0.36783026,  0.9541552 ],
       [ 1.35683157, -1.80789821,  1.1261168 ,  0.54660937],
       [ 0.1596564 , -0.80384428, -0.06714768,  0.33367579]])

In [2]:
_2D=np.arange(20).reshape(5,4)
_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
_2D[3,2]

14

In [8]:
_2D[1]

array([4, 5, 6, 7])

In [19]:
_2D[2:4,1:3]

2

In [20]:
_2D[2:4,1:3].ndim #ndim to check dimension

2

In [37]:
_2D[0:4,0:4] #slicing

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.size(_2D[0:4,0:4])

16

In [39]:
_2D[:,1]

array([ 1,  5,  9, 13, 17])

In [42]:
_2D[2,] #selection

array([ 8,  9, 10, 11])

In [44]:
d3=np.arange(100).reshape(5,5,4)
d3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [48]:
d3[2:4,2:4,2:4]

array([[[50, 51],
        [54, 55]],

       [[70, 71],
        [74, 75]]])

In [49]:
a=np.arange(10)
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
np.sum(a>3)

6

In [51]:
a[::-1] #for reverse array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [52]:
alist=[11,22,33,44,55,66,77,88,99]

In [55]:
alist[-3:-6:-1] #reverse me slicing karega lekin stpe -1 kar k hoga

[77, 66, 55]

In [56]:
alist[::-3]

[99, 66, 33]

In [59]:
d2=np.arange(49).reshape(7,7)
d2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [76]:
d2[[0,3,6],1:4]

array([[ 1,  2,  3],
       [22, 23, 24],
       [43, 44, 45]])

In [77]:
d2[[0,2,4],[1,3,5]]

array([ 1, 17, 33])

In [78]:
#ravel will only flat the dimensions

In [6]:
m=np.arange(10,19).reshape(3,3)
m

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [20]:
print(f"{m.min()} min of the entire matrix")

10 min of the entire matrix


In [21]:
print(f"{m.max()} max of the entire matrix")

18 max of the entire matrix


In [14]:
print(f"({m.argmin()} position of the min value)")

(0 position of the min value)


In [15]:
print(f"({m.argmax()} position of the max value)")

(8 position of the max value)


In [51]:
print(f"({m.min(axis=0)} mins down each column)")

([10 11 12] mins down each column)


In [52]:
print(f"({m.min(axis=1)} mins down each row)")

([10 13 16] mins down each row)


In [53]:
print(f"({m.max(axis=0)} max down each column)")

([16 17 18] max down each column)


In [54]:
print(f"({m.max(axis=1)} max down each row)")

([12 15 18] max down each row)


In [40]:
z=np.arange(1,10)
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
z.mean(), z.std(), z.var() 

(5.0, 2.581988897471611, 6.666666666666667)

In [42]:
z.sum(), z.prod()

(45, 362880)

In [43]:
z.cumsum(), z.cumprod()

(array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32),
 array([     1,      2,      6,     24,    120,    720,   5040,  40320,
        362880], dtype=int32))

In [46]:
(z<5).all(), (z<5).any()

(False, True)

In [49]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
print('Horizontal Split',np.hsplit(a,4))

Horizontal Split [array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [62]:
np.split(a,[1,3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([], shape=(0, 4), dtype=int32)]

In [9]:
sh=np.arange(9).reshape(3,3)

In [10]:
sh

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
sh[:2,1:]

array([[1, 2],
       [4, 5]])

In [23]:
sh[2], sh[2,:], sh[2:,:]

(array([6, 7, 8]), array([6, 7, 8]), array([[6, 7, 8]]))

In [33]:
sh[:,2] ,sh[:,:1]

(array([2, 5, 8]), array([[0],
        [3],
        [6]]))

# Boolean Indexing

In [34]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [47]:
data=np.random.randn(7,4)

In [48]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [49]:
data

array([[ 2.10995154, -2.64192134,  0.08173731,  1.06630355],
       [-0.27547116, -1.25003588, -0.61690675, -0.58387998],
       [ 0.36979547,  0.96373344, -2.0882955 , -0.27935586],
       [ 0.90421087,  0.91314126,  0.19412296,  0.28298731],
       [-1.30861908,  0.75262881,  1.83855724,  1.21062789],
       [ 0.11734998,  0.54331609,  0.22926604, -0.80683037],
       [ 1.53429461,  0.63824489,  1.63102299,  0.11625461]])

In [50]:
print(names=='Bob')

[ True False False  True False False False]


In [51]:
data[names=='Bob']

array([[ 2.10995154, -2.64192134,  0.08173731,  1.06630355],
       [ 0.90421087,  0.91314126,  0.19412296,  0.28298731]])

In [57]:
data[names =='Bob', 2:] #column bata rahe hen coma k baad 

array([[0.08173731, 1.06630355],
       [0.19412296, 0.28298731]])

In [58]:
data[names =='Bob', 3]

array([1.06630355, 0.28298731])

In [59]:
data[names !='Bob']

array([[-0.27547116, -1.25003588, -0.61690675, -0.58387998],
       [ 0.36979547,  0.96373344, -2.0882955 , -0.27935586],
       [-1.30861908,  0.75262881,  1.83855724,  1.21062789],
       [ 0.11734998,  0.54331609,  0.22926604, -0.80683037],
       [ 1.53429461,  0.63824489,  1.63102299,  0.11625461]])

In [62]:
data[~(names=='Bob')]

array([[-0.27547116, -1.25003588, -0.61690675, -0.58387998],
       [ 0.36979547,  0.96373344, -2.0882955 , -0.27935586],
       [-1.30861908,  0.75262881,  1.83855724,  1.21062789],
       [ 0.11734998,  0.54331609,  0.22926604, -0.80683037],
       [ 1.53429461,  0.63824489,  1.63102299,  0.11625461]])

In [67]:
arr=np.arange(15).reshape(3,5)

In [68]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [73]:
arr=np.arange(16).reshape(2,2,4)

In [74]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [78]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [79]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [89]:
m1=np.arange(12).reshape(3,4)
m2=np.array([[4,5,6,7],[3,4,5,6],[7,8,9,5]])

In [90]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
m2

array([[4, 5, 6, 7],
       [3, 4, 5, 6],
       [7, 8, 9, 5]])

In [92]:
m1*m2 # ye element wise he, is k liye row column ki condition nai

array([[ 0,  5, 12, 21],
       [12, 20, 30, 42],
       [56, 72, 90, 55]])

In [93]:
m1.dot(m2)  #yahan row column wali condition satisfy honi chye

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [94]:
m3=np.array([[4,5,6,7],[3,4,5,6],[7,8,9,5],[4,7,2,5]])

In [95]:
m1.dot(m3)

array([[ 29,  41,  29,  31],
       [101, 137, 117, 123],
       [173, 233, 205, 215]])

In [96]:
m1@m3

array([[ 29,  41,  29,  31],
       [101, 137, 117, 123],
       [173, 233, 205, 215]])

In [97]:
np.dot(m1,m3)

array([[ 29,  41,  29,  31],
       [101, 137, 117, 123],
       [173, 233, 205, 215]])

In [98]:
X=np.random.rand(5,5)

In [99]:
X

array([[0.84264056, 0.71090626, 0.57649908, 0.65122281, 0.90790929],
       [0.35547035, 0.02026364, 0.48027207, 0.37904854, 0.39679177],
       [0.94988161, 0.99076485, 0.66693672, 0.34369108, 0.09909792],
       [0.85966963, 0.31106172, 0.3824943 , 0.87814751, 0.13078372],
       [0.50790877, 0.00200987, 0.93190755, 0.76357102, 0.67095088]])

In [100]:
mat=X.T.dot(X)

In [101]:
mat

array([[2.73568055, 1.81578202, 2.09215766, 2.15269427, 1.45343281],
       [1.81578202, 1.58417674, 1.20119866, 1.08584907, 0.7936919 ],
       [2.09215766, 1.20119866, 2.0225706 , 1.83416   , 1.45535713],
       [2.15269427, 1.08584907, 1.83416   , 2.04007627, 1.40287969],
       [1.45343281, 0.7936919 , 1.45535713, 1.40287969, 1.45884284]])

In [103]:
from numpy.linalg import inv , qr

In [104]:
inv(mat)

array([[126.08777605, -81.72611868, -14.1926607 , -90.6851987 ,
         20.20852446],
       [-81.72611868,  54.13732962,   8.39009368,  58.74431133,
        -12.89153371],
       [-14.1926607 ,   8.39009368,   5.52293453,   8.11645568,
         -3.73948685],
       [-90.6851987 ,  58.74431133,   8.11645568,  68.00167604,
        -15.10138871],
       [ 20.20852446, -12.89153371,  -3.73948685, -15.10138871,
          5.81823726]])

In [105]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  1.42108547e-14,  2.66453526e-15,
        -1.06581410e-14,  7.10542736e-15],
       [-7.10542736e-15,  1.00000000e+00,  4.44089210e-15,
         1.06581410e-14, -1.77635684e-15],
       [ 3.19744231e-14,  3.90798505e-14,  1.00000000e+00,
        -3.55271368e-15, -5.32907052e-15],
       [-1.42108547e-14,  1.06581410e-14,  1.77635684e-15,
         1.00000000e+00,  1.77635684e-15],
       [ 2.84217094e-14, -1.06581410e-14, -3.55271368e-15,
        -3.55271368e-15,  1.00000000e+00]])