In [4]:
#Vectorized is something which has position.

In [5]:
alist=[1,2,3,4,5]
empty=[]
for num in alist:
    empty.append(num*5)
empty

[5, 10, 15, 20, 25]

In [2]:
import numpy as np #numpy is fast and works on vectorization

In [3]:
numbers=np.array([2,3,4,6,7,8])
numbers*4

array([ 8, 12, 16, 24, 28, 32])

In [8]:
from numpy import *

In [21]:
numbers=array([2,3,4,6,7,8])
no=numbers*4
no

array([ 8, 12, 16, 24, 28, 32])

In [22]:
no >10

array([False,  True,  True,  True,  True,  True])

In [12]:
a1=np.array([2,3,4,4.0,5.0])
a1

array([2., 3., 4., 4., 5.])

In [13]:
a2=np.array([2,3,4,4.0,5.0],dtype=int)
a2

array([2, 3, 4, 4, 5])

In [14]:
def squares (values):
    result=[]
    for v in values:
        result.append(v*v)
    return result

In [15]:
to_square=range(100000)

In [17]:
%timeit squares(to_square) #any keyword with % sign is magic function

16.7 ms ± 56.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
array_square=np.arange(100000)

In [19]:
%timeit array_square**2

156 µs ± 484 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
type(a2)

numpy.ndarray

In [26]:
np.size(a2)

5

In [28]:
len(a2)

5

In [29]:
a3=np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
q=np.ones(5)
q

array([1., 1., 1., 1., 1.])

In [36]:
np.zeros_like(q)

array([0., 0., 0., 0., 0.])

In [40]:
np.ones_like(q)

array([1., 1., 1., 1., 1.])

In [42]:
x=np.array([3,6,9])
np.ones_like(x)

array([1, 1, 1])

In [51]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [58]:
a1+a2

array([ 4.,  6.,  8.,  8., 10.])

# 2D Numpy

In [78]:
_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [79]:
_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
np.size(_2d)

12

In [81]:
len(_2d)

4

In [82]:
_2d.shape

(4, 3)

In [99]:
_2D=np.arange(20).reshape(5,4)
_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [100]:
np.size(_2D)

20

In [101]:
np.size(_2D,0) #ye rows batayega

5

In [103]:
np.size(_2D,1) #ye columns batarega

4

In [104]:
np.shape(_2D)

(5, 4)

In [106]:
_2D.reshape(20) #It is one dimension.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
import math
tdarray=np.random.randn(20).reshape(5,4)
tdarray

array([[-0.1251118 , -0.0540305 ,  1.11397485, -0.64487159],
       [-0.12166057, -1.45964744, -0.27998011,  2.2346097 ],
       [ 0.11485135, -1.23472826,  0.36783026,  0.9541552 ],
       [ 1.35683157, -1.80789821,  1.1261168 ,  0.54660937],
       [ 0.1596564 , -0.80384428, -0.06714768,  0.33367579]])

In [15]:
_2D=np.arange(20).reshape(5,4)
_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
_2D[3,2]

14

In [17]:
_2D[1,]

array([4, 5, 6, 7])

In [19]:
_2D[2:4,1:3]

2

In [20]:
_2D[2:4,1:3].ndim #ndim to check dimension

2

In [37]:
_2D[0:4,0:4] #slicing

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.size(_2D[0:4,0:4])

16

In [39]:
_2D[:,1]

array([ 1,  5,  9, 13, 17])

In [42]:
_2D[2,] #selection

array([ 8,  9, 10, 11])

In [44]:
d3=np.arange(100).reshape(5,5,4)
d3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [48]:
d3[2:4,2:4,2:4]

array([[[50, 51],
        [54, 55]],

       [[70, 71],
        [74, 75]]])

In [49]:
a=np.arange(10)
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
np.sum(a>3)

6

In [51]:
a[::-1] #for reverse array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [52]:
alist=[11,22,33,44,55,66,77,88,99]

In [55]:
alist[-3:-6:-1] #reverse me slicing karega lekin stpe -1 kar k hoga

[77, 66, 55]

In [56]:
alist[::-3]

[99, 66, 33]

In [59]:
d2=np.arange(49).reshape(7,7)
d2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [76]:
d2[[0,3,6],1:4]

array([[ 1,  2,  3],
       [22, 23, 24],
       [43, 44, 45]])

In [77]:
d2[[0,2,4],[1,3,5]]

array([ 1, 17, 33])

In [78]:
#ravel will only flat the dimensions