In [4]:
#Vectorized is something which has position.

In [5]:
alist=[1,2,3,4,5]
empty=[]
for num in alist:
    empty.append(num*5)
empty

[5, 10, 15, 20, 25]

In [7]:
import numpy as np #numpy is fast and works on vectorization

In [3]:
numbers=np.array([2,3,4,6,7,8])
numbers*4

array([ 8, 12, 16, 24, 28, 32])

In [8]:
from numpy import *

In [21]:
numbers=array([2,3,4,6,7,8])
no=numbers*4
no

array([ 8, 12, 16, 24, 28, 32])

In [22]:
no >10

array([False,  True,  True,  True,  True,  True])

In [12]:
a1=np.array([2,3,4,4.0,5.0])
a1

array([2., 3., 4., 4., 5.])

In [13]:
a2=np.array([2,3,4,4.0,5.0],dtype=int)
a2

array([2, 3, 4, 4, 5])

In [14]:
def squares (values):
    result=[]
    for v in values:
        result.append(v*v)
    return result

In [15]:
to_square=range(100000)

In [17]:
%timeit squares(to_square) #any keyword with % sign is magic function

16.7 ms ± 56.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
array_square=np.arange(100000)

In [19]:
%timeit array_square**2

156 µs ± 484 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
type(a2)

numpy.ndarray

In [26]:
np.size(a2)

5

In [28]:
len(a2)

5

In [29]:
a3=np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
q=np.ones(5)
q

array([1., 1., 1., 1., 1.])

In [36]:
np.zeros_like(q)

array([0., 0., 0., 0., 0.])

In [40]:
np.ones_like(q)

array([1., 1., 1., 1., 1.])

In [42]:
x=np.array([3,6,9])
np.ones_like(x)

array([1, 1, 1])

In [51]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [58]:
a1+a2

array([ 4.,  6.,  8.,  8., 10.])

# 2D Numpy

In [78]:
_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [79]:
_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
np.size(_2d)

12

In [81]:
len(_2d)

4

In [82]:
_2d.shape

(4, 3)

In [99]:
_2D=np.arange(20).reshape(5,4)
_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [100]:
np.size(_2D)

20

In [101]:
np.size(_2D,0) #ye rows batayega

5

In [103]:
np.size(_2D,1) #ye columns batarega

4

In [104]:
np.shape(_2D)

(5, 4)

In [106]:
_2D.reshape(20) #It is one dimension.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])